development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: myapp
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: mmsaZaidi@gmail.com
  password: RuWbZx6
production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: msaZaidi@gmail.com  
  password: RuWbdZx6